config = {
    "tile-size": 64,
    "z-order": {"background": 0, "target": 5, "actor": 10, "ui": 15},
    "actor": {"speed": 0.15, "delay": 16.66},
}

styles = {
    "actor/0": "examples/assets/sample/alien-green.png",
    "actor/1": "examples/assets/sample/alien-blue.png",
    "actor/2": "examples/assets/sample/alien-red.png",
    "actor/3": "examples/assets/sample/alien-yellow.png",
    "actor/4": "examples/assets/sample/alien-grey.png",
    "entity/0": "examples/assets/sample/box.png",
    "entity/1": "examples/assets/sample/castle.png",
    "entity/2": "examples/assets/sample/flower.png",
    "entity/3": "examples/assets/sample/igloo.png",
    "entity/4": "examples/assets/sample/mashroom-1.png",
    "entity/5": "examples/assets/sample/mashroom-2.png",
    "entity/6": "examples/assets/sample/mashroom-3.png",
    "entity/7": "examples/assets/sample/pyramid.png",
    "entity/8": "examples/assets/sample/snowman.png",
    "entity/9": "examples/assets/sample/tree-1.png",
    "entity/10": "examples/assets/sample/tree-2.png",
    "entity/11": "examples/assets/sample/tree-3.png",
    "tile/0": "examples/assets/sample/green.png",
    "tile/1": "examples/assets/sample/grey.png",
    "tile/2": "examples/assets/sample/yellow.png",
    "tile/3": "examples/assets/sample/blue.png",
    "ui/0": "examples/assets/sample/ui.png",
}
